//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILocationService")]
    public interface ILocationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/GetLocationByLocality", ReplyAction="http://tempuri.org/ILocationService/GetLocationByLocalityResponse")]
        string GetLocationByLocality(string locality);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/GetLocationByLocality", ReplyAction="http://tempuri.org/ILocationService/GetLocationByLocalityResponse")]
        System.Threading.Tasks.Task<string> GetLocationByLocalityAsync(string locality);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/GetLocationByZip", ReplyAction="http://tempuri.org/ILocationService/GetLocationByZipResponse")]
        string GetLocationByZip(string zip);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocationService/GetLocationByZip", ReplyAction="http://tempuri.org/ILocationService/GetLocationByZipResponse")]
        System.Threading.Tasks.Task<string> GetLocationByZipAsync(string zip);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationServiceChannel : ConsoleApplication1.ServiceReference1.ILocationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.ILocationService>, ConsoleApplication1.ServiceReference1.ILocationService {
        
        public LocationServiceClient() {
        }
        
        public LocationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetLocationByLocality(string locality) {
            return base.Channel.GetLocationByLocality(locality);
        }
        
        public System.Threading.Tasks.Task<string> GetLocationByLocalityAsync(string locality) {
            return base.Channel.GetLocationByLocalityAsync(locality);
        }
        
        public string GetLocationByZip(string zip) {
            return base.Channel.GetLocationByZip(zip);
        }
        
        public System.Threading.Tasks.Task<string> GetLocationByZipAsync(string zip) {
            return base.Channel.GetLocationByZipAsync(zip);
        }
    }
}
